env:
  es2021: true
  node: true
root: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
  tsconfigRootDir: .
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': 'error'
  no-console: 'warn'
  no-unused-vars: 'warn'
  import/extensions: 'off'
  import/prefer-default-export: 'off'
  no-shadow: 'off'
  max-len: ['warn', { code: 120, ignoreComments: true, ignoreUrls: true }]
  semi: 'error'
  indent: ['warn', 2]
  quotes: ['warn', 'single']
  no-extra-boolean-cast: 'off'
